language: node_js
node_js:
  - 10

branches:
  only:
    - master

cache: npm

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: b5417d8d-65ca-4329-8163-a23289f43502
